### ISSUE TITLE
Some vulp helmet sprites do not work

### ISSUE THREAD

**Issue by 0x6273** [new-frontiers-14/frontier-station-14#1043]
## Description

For some hardsuits that have custom vulp helmet sprites, it shows the regular sprite instead.

**Reproduction**

- Be vulp
- Put atmos hardsuit on
- Toggle helmet

**Screenshots**

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/48867431/a1a52227-0e69-43fe-9ab9-2dff662fa5f8)

**Additional context**

All the ones that don't work seem to specify the rsi states manually in the prototype:
```yaml
  - type: Clothing
    clothingVisuals:
      head:
      - state: equipped-head
      - state: equipped-head-unshaded
        shader: unshaded
```

The ones that do work, only specify rsi path:
```yaml
  - type: Clothing
    sprite: Clothing/Head/Hardsuits/engineering.rsi
```
