### ISSUE TITLE
Laughin' Syrup does not work, making laughin' peas worthless.

### ISSUE THREAD

**Issue by MciReloaded** [new-frontiers-14/frontier-station-14#1140]
## Description

Laughin' Peas generate somehing called laughin' syrup. It's SUPPOSED to make someone laugh when ingested, however- it does not. It's just a sweet chemical. 
**Reproduction**

Consume laughin' syrup. No laughter happens.
**Screenshots**

**Additional context**

I know what it's _supposed_ to do, as it  works just fine over on DeltaV.

**Comment by MciReloaded** [comment]
Well in excess of 50U At the time of posting.

**Comment by whatston3** [comment]
> It has a 30% chance to cause laughter each tick. How much Syrup did you consume?

This is Laughter.

LaughinSyrup as-is, both here and upstream, is a condiment with a definition without effects.  If it metabolized into Laughter and Sugar (since it's syrup), this could make sense.  As a potential fix, a definition like the one below produces giggles, and a little extra nutrition if put on a cake or pancake to provide an incentive for use in-game.

```
- type: reagent
  id: LaughinSyrup
  name: reagent-name-laughin-syrup
  group: Foods
  desc: reagent-desc-laughin-syrup
  physicalDesc: reagent-physical-desc-funny
  flavor: sweet
  color: "#803280"
  recognizable: true
  metabolisms:
    Food:
      effects:
      - !type:AdjustReagent
        reagent: Sugar
        amount: 0.2
      - !type:AdjustReagent
        reagent: Laughter
        amount: 0.3
```

Instead of decomposition into Laughter, it might also be interesting to create a second laughing effect.  If combined with Laughter, you could create a chaos keg that makes you laugh even harder.
